### ISSUE TITLE
unhandled exception when i don't pass a day to `... test one`

### ISSUE THREAD

**Issue by kaczmarj** [SaahilClaypool/aoc_2021#1]
when i run the following

```
dotnet  Aoc.Csharp/bin/Debug/net6.0/Aoc.Csharp.dll test one
```

i get the following traceback

```
Failed to run app: Command 'one' is missing required argument 'Day'.
Unhandled exception. Spectre.Console.Cli.CommandRuntimeException: Command 'one' is missing required argument 'Day'.
   at Spectre.Console.Cli.CommandValidator.ValidateRequiredParameters(CommandTree tree) in /_/src/Spectre.Console/Cli/Internal/CommandValidator.cs:line 17
   at Spectre.Console.Cli.CommandValueResolver.GetParameterValues(CommandTree tree, ITypeResolver resolver) in /_/src/Spectre.Console/Cli/Internal/Binding/CommandValueResolver.cs:line 14
   at Spectre.Console.Cli.CommandBinder.Bind(CommandTree tree, Type settingsType, ITypeResolver resolver) in /_/src/Spectre.Console/Cli/Internal/CommandBinder.cs:line 9
   at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in /_/src/Spectre.Console/Cli/Internal/CommandExecutor.cs:line 103
   at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in /_/src/Spectre.Console/Cli/Internal/CommandExecutor.cs:line 84
   at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in /_/src/Spectre.Console/Cli/CommandApp.cs:line 87
   at Spectre.Console.Cli.CommandApp.Run(IEnumerable`1 args) in /_/src/Spectre.Console/Cli/CommandApp.cs:line 61
   at Aoc.Runner.Cli.Run(String[] args) in /opt/aoc_2021/Aoc.Runner/Cli.cs:line 15
   at Aoc.Runner.AocRunner.Run(String[] args) in /opt/aoc_2021/Aoc.Runner/AocRunner.cs:line 15
   at Program.<Main>$(String[] args) in /opt/aoc_2021/Aoc.Csharp/Program.cs:line 3
Aborted (core dumped)
root@ab14548e81ec:/opt/aoc_2021# dotnet  Aoc.Csharp/bin/Debug/net6.0/Aoc.Csharp.dll test one
Failed to run app: Command 'one' is missing required argument 'Day'.
Unhandled exception. Spectre.Console.Cli.CommandRuntimeException: Command 'one' is missing required argument 'Day'.
   at Spectre.Console.Cli.CommandValidator.ValidateRequiredParameters(CommandTree tree) in /_/src/Spectre.Console/Cli/Internal/CommandValidator.cs:line 17
   at Spectre.Console.Cli.CommandValueResolver.GetParameterValues(CommandTree tree, ITypeResolver resolver) in /_/src/Spectre.Console/Cli/Internal/Binding/CommandValueResolver.cs:line 14
   at Spectre.Console.Cli.CommandBinder.Bind(CommandTree tree, Type settingsType, ITypeResolver resolver) in /_/src/Spectre.Console/Cli/Internal/CommandBinder.cs:line 9
   at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in /_/src/Spectre.Console/Cli/Internal/CommandExecutor.cs:line 103
   at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in /_/src/Spectre.Console/Cli/Internal/CommandExecutor.cs:line 84
   at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in /_/src/Spectre.Console/Cli/CommandApp.cs:line 87
   at Spectre.Console.Cli.CommandApp.Run(IEnumerable`1 args) in /_/src/Spectre.Console/Cli/CommandApp.cs:line 61
   at Aoc.Runner.Cli.Run(String[] args) in /opt/aoc_2021/Aoc.Runner/Cli.cs:line 15
   at Aoc.Runner.AocRunner.Run(String[] args) in /opt/aoc_2021/Aoc.Runner/AocRunner.cs:line 15
   at Program.<Main>$(String[] args) in /opt/aoc_2021/Aoc.Csharp/Program.cs:line 3
Aborted (core dumped)
```

**Comment by SaahilClaypool** [comment]
RTFM

**Comment by SaahilClaypool** [comment]
`dotnet run -- run all `

**Comment by SaahilClaypool** [comment]
The error's are not captured by the parser context because that would also swallow errors from the actual test context. That could be fixed by catching specific types of errors (E.g., argument errors from the parser.) 

PR's welcome
